name: DefaultCI

on:
  push:
    branches:
      - master
  # Update the image every now and then

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  default-build:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: checkout

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: altv-server
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push To ${{ vars.REGISTRY_URL }}
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ vars.REGISTRY_URL }}/kampfmodz
          username: a
          password: b

